[workspace]
members = [
  "crates/rsdos",
  "crates/pyrsdos",
]
default-members = [
  "crates/rsdos"
]

resolver = "2"

[workspace.package]
authors = ["Jusong Yu <jusong.d.yu@gmail.com>"]
rust-version = "1.76.0"
edition = "2021"

