name: CI-rs
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    name: testing-${{ matrix.toolchain }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - toolchain: 1.78.0 # test MSRV
            os: ubuntu-latest
          - toolchain: nightly
            os: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: Log active toolchain
        run: rustup show
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
      - name: Run cargo test in release mode
        run: cargo test --all --release
